version: '3.9'
services:
  web:
    image: php:7.4.33-apache
    container_name: php7.4.33-ivms
    ports:
      - "8801:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb
    container_name: mariadb-ivms
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IVMS
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8181:8080"
    depends_on:
      - db
